package com.call.colorscreen.ledflash.analystic;

public interface EventKey {
    String SPLASH_SHOW = "SPLASH_SHOW";
    String MAIN_SHOW = "MAIN_SHOW";
    String MAIN_SETTING_CLICKED = "MAIN_SETTING_CLICKED";
    String MAINDIALOG_OPEN = "MAINDIALOG_OPEN";
    String MAINDIALOG_VIDEOS_CLICKED  = "MAINDIALOG_VIDEOS_CLICKED";
    String MAINDIALOG_IMAGES_CLICKED  = "MAINDIALOG_IMAGES_CLICKED";

    String APPLY_SHOW = "APPLY_SHOW";
    String APPLY_BACK_CLICKED = "APPLY_BACK_CLICKED";
    String APPLY_DELETE_CLICKED = "APPLY_DELETE_CLICKED";
    String APPLY_APPLY_CLICKED = "APPLY_APPLY_CLICKED";
    String APPLY_CONTACT_CLICKED = "APPLY_CONTACT_CLICKED";
    String SETTING_SHOW = "SETTING_SHOW";
    String SETTING_BACK_CLICKED = "SETTING_BACK_CLICKED";
    String SETTING_SHAREAPP_CLICKED = "SETTING_SHAREAPP_CLICKED";
    String SETTING_CHECKUPDATE_CLICKED = "SETTING_CHECKUPDATE_CLICKED";
    String SETTING_POLICY_CLICKED = "SETTING_POLICY_CLICKED";
    String SETTING_FLASH_CLICKED = "SETTING_FLASH_CLICKED";
    String SETTING_RATE_CLICKED = "SETTING_RATE_CLICKED";

    String CALL_SHOW = "CALL_SHOW";
    String CALL_ACCETP_CALL = "CALL_ACCETP_CALL";
    String CALL_REJECT_CALL = "CALL_REJECT_CALL";
}
